version: '3.9'

services:
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - mysql
      - app

  #Database Service
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: 123456

  app:
    container_name: testDocker
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    working_dir: /var/www